### Create Employee
POST http://localhost:3000/api/emp
Content-Type: application/json

{
  "name": "emp",
  "email": "emp1@example.com",
  "mobile": 910,
  "designation": "dev",
  "companyName": "google"
}


### Get All Employees
GET http://localhost:3000/api/emp


### Update Employee
PUT http://localhost:3000/api/emp/69ec8c5f85dec82092509c6b
Content-Type: application/json

{
  "designation": "dev",
  "companyName": "Microsoft"
}


### Delete Employee
DELETE http://localhost:3000/api/emp/<id>