### ================= USERS =================

### Get all users
GET http://localhost:4000/user-api/users

###

### Get user by ID
GET http://localhost:4000/user-api/users/69aa69883585168f26974fde

###

### Create user
POST http://localhost:4000/user-api/users
Content-Type: application/json

{
  "username": "Ramu17",
  "email": "ramu1798@gmail.com",
  "password": "ramu1798"
}

###

### Update user
PUT http://localhost:4000/user-api/users/69aa69883585168f26974fde
Content-Type: application/json

{
  "username": "aizen",
  "email": "aizen27@gmail.com",
  "password": "aizen123"
}

###

### Delete user
DELETE http://localhost:4000/user-api/users/69aa69883585168f26974fde



### ================= PRODUCTS =================

### Get all products
GET http://localhost:4000/product-api/products

###

### Get product by productID
GET http://localhost:4000/product-api/products/101

###

### Create product
POST http://localhost:4000/product-api/products
Content-Type: application/json

{
  "productID": 101,
  "productName": "cashews",
  "price": 13000,
  "brand": "alhabibi"
}

###

### Update product
PUT http://localhost:4000/product-api/products/100010
Content-Type: application/json

{
  "productName": "blueberries",
  "price": 10000,
  "brand": "alhabibi"
}

###

### Delete product
DELETE http://localhost:4000/product-api/products/101